apiVersion: v1
kind: Service
metadata:
  name: awesome-media-frontend
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: awesome-media-frontend
  type: NodePort