apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: awesome-media-frontend
  labels:
    app: awesome-media-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awesome-media-frontend
  template:
    metadata:
      labels:
        app: awesome-media-frontend
    spec:
      containers:
      - name: awesome-media-frontend
        image: jisang/awesome-media-frontend:1.0 
        #icp.ghama.io:8500/ns-edu15/awesome-media-frontend:1.0
        ports:
        - containerPort: 8080        
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s      
        resources:
          requests:
            memory: "250Mi"
            cpu: "45m"
          limits:
            memory: "800Mi"
            cpu: "0.45"